export const beefAbi = [
  { type: "constructor", inputs: [], stateMutability: "nonpayable" },
  { type: "fallback", stateMutability: "payable" },
  {
    type: "function",
    name: "WETH",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IERC20" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "WSTETH",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IERC20" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "arbiterAttend",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "arbiters",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "arbitersRequiredCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "arbitersRewardBasisPoints",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "attendCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "beefGone",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "challenger",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "cooking",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "description",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getInfo",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct Beef.BeefInfo",
        components: [
          {
            name: "params",
            type: "tuple",
            internalType: "struct Beef.ConstructorParams",
            components: [
              { name: "owner", type: "address", internalType: "address" },
              { name: "wager", type: "uint256", internalType: "uint256" },
              { name: "challenger", type: "address", internalType: "address" },
              { name: "settleStart", type: "uint256", internalType: "uint256" },
              { name: "title", type: "string", internalType: "string" },
              { name: "description", type: "string", internalType: "string" },
              {
                name: "arbiters",
                type: "address[]",
                internalType: "address[]",
              },
              {
                name: "joinDeadline",
                type: "uint256",
                internalType: "uint256",
              },
              { name: "staking", type: "bool", internalType: "bool" },
            ],
          },
          { name: "cooking", type: "bool", internalType: "bool" },
          { name: "resultYes", type: "uint128", internalType: "uint128" },
          { name: "resultNo", type: "uint128", internalType: "uint128" },
          { name: "attendCount", type: "uint256", internalType: "uint256" },
          { name: "beefGone", type: "bool", internalType: "bool" },
          {
            name: "protocolRewardBasisPoints",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "arbitersRewardBasisPoints",
            type: "uint256",
            internalType: "uint256",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasAttended",
    inputs: [{ name: "arbiter", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasSettled",
    inputs: [{ name: "arbiter", type: "address", internalType: "address" }],
    outputs: [{ name: "result", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "initialize",
    inputs: [
      {
        name: "params",
        type: "tuple",
        internalType: "struct Beef.ConstructorParams",
        components: [
          { name: "owner", type: "address", internalType: "address" },
          { name: "wager", type: "uint256", internalType: "uint256" },
          { name: "challenger", type: "address", internalType: "address" },
          { name: "settleStart", type: "uint256", internalType: "uint256" },
          { name: "title", type: "string", internalType: "string" },
          { name: "description", type: "string", internalType: "string" },
          { name: "arbiters", type: "address[]", internalType: "address[]" },
          { name: "joinDeadline", type: "uint256", internalType: "uint256" },
          { name: "staking", type: "bool", internalType: "bool" },
        ],
      },
      { name: "amountOutMin", type: "uint256", internalType: "uint256" },
      { name: "_weth", type: "address", internalType: "address" },
      { name: "_wsteth", type: "address", internalType: "address" },
      { name: "_uniswapV2Router", type: "address", internalType: "address" },
      {
        name: "_slaughterhouse",
        type: "address",
        internalType: "address payable",
      },
      {
        name: "_protocolRewardBasisPoints",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "_arbitersRewardBasisPoints",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "joinBeef",
    inputs: [{ name: "amountOutMin", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "joinDeadline",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "protocolRewardBasisPoints",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "resultNo",
    inputs: [],
    outputs: [{ name: "", type: "uint128", internalType: "uint128" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "resultYes",
    inputs: [],
    outputs: [{ name: "", type: "uint128", internalType: "uint128" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "serveBeef",
    inputs: [{ name: "amountOutMin", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "settleBeef",
    inputs: [{ name: "verdict", type: "bool", internalType: "bool" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "settleStart",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "settlingDuration",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "slaughterhouse",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract Slaughterhouse" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "staking",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "title",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalBasisPoints",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "uniswapV2Router",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract IUniswapV2Router02",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "wager",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "withdrawRaw",
    inputs: [{ name: "amountOutMin", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "withdrawRotten",
    inputs: [{ name: "amountOutMin", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "ArbiterAttended",
    inputs: [
      {
        name: "arbiter",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  { type: "event", name: "BeefCooking", inputs: [], anonymous: false },
  {
    type: "event",
    name: "BeefCreated",
    inputs: [
      {
        name: "owner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "challenger",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "wager",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "settleStart",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      { name: "title", type: "string", indexed: false, internalType: "string" },
      {
        name: "description",
        type: "string",
        indexed: false,
        internalType: "string",
      },
      {
        name: "arbiters",
        type: "address[]",
        indexed: false,
        internalType: "address[]",
      },
      {
        name: "protocolRewardBasisPoints",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "arbitersRewardBasisPoints",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "BeefServed",
    inputs: [
      {
        name: "winner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "BeefSettled",
    inputs: [
      {
        name: "arbiter",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      { name: "verdict", type: "bool", indexed: false, internalType: "bool" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "BeefWithdrawn",
    inputs: [
      {
        name: "hadBeenCooking",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Initialized",
    inputs: [
      {
        name: "version",
        type: "uint64",
        indexed: false,
        internalType: "uint64",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "BeefAlreadyGone", inputs: [] },
  {
    type: "error",
    name: "BeefArbiterAlreadyAttended",
    inputs: [{ name: "sender", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "BeefArbiterAlreadySettled",
    inputs: [{ name: "sender", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "BeefInvalidArbitersCount",
    inputs: [
      { name: "providedCount", type: "uint256", internalType: "uint256" },
      { name: "requiredCount", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "BeefInvalidWager",
    inputs: [
      { name: "declaredWager", type: "uint256", internalType: "uint256" },
      { name: "providedWager", type: "uint256", internalType: "uint256" },
    ],
  },
  { type: "error", name: "BeefIsCooking", inputs: [] },
  {
    type: "error",
    name: "BeefIsNotCooked",
    inputs: [
      { name: "deadline", type: "uint256", internalType: "uint256" },
      { name: "timestamp", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "BeefIsRotten",
    inputs: [
      { name: "deadline", type: "uint256", internalType: "uint256" },
      { name: "timestamp", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "BeefNotArbiter",
    inputs: [{ name: "sender", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "BeefNotChallenger",
    inputs: [
      { name: "declaredChallenger", type: "address", internalType: "address" },
      { name: "sender", type: "address", internalType: "address" },
    ],
  },
  {
    type: "error",
    name: "BeefNotOwner",
    inputs: [
      { name: "declaredOwner", type: "address", internalType: "address" },
      { name: "sender", type: "address", internalType: "address" },
    ],
  },
  {
    type: "error",
    name: "BeefNotOwnerNorChallenger",
    inputs: [
      { name: "declaredOwner", type: "address", internalType: "address" },
      { name: "declaredChallenger", type: "address", internalType: "address" },
      { name: "sender", type: "address", internalType: "address" },
    ],
  },
  { type: "error", name: "BeefNotRaw", inputs: [] },
  {
    type: "error",
    name: "BeefNotRotten",
    inputs: [
      { name: "deadline", type: "uint256", internalType: "uint256" },
      { name: "timestamp", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "BeefNotSettled",
    inputs: [
      { name: "resultYes", type: "uint128", internalType: "uint128" },
      { name: "resultNo", type: "uint128", internalType: "uint128" },
      { name: "requiredSettleCount", type: "uint256", internalType: "uint256" },
    ],
  },
  { type: "error", name: "EthTransferFailed", inputs: [] },
  { type: "error", name: "InvalidInitialization", inputs: [] },
  { type: "error", name: "NotInitializing", inputs: [] },
  {
    type: "error",
    name: "OwnableInvalidOwner",
    inputs: [{ name: "owner", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "OwnableUnauthorizedAccount",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
  },
  { type: "error", name: "OwnershipTransferDisabled", inputs: [] },
] as const
